### ISSUE TITLE
Linux版本读取注册信息错误

### ISSUE THREAD

**Issue by ALICEOFALICE** [Hsury/Bilibili-Toolkit#11]
Linux版本读取到的信息错误，注册时间读取错误
平台Linux centos7
![image](https://user-images.githubusercontent.com/41146748/62445343-95edab00-b792-11e9-9fff-ca3045b063ab.png)

**Comment by Hsury** [comment]
这并非操作系统或脚本方面的问题，而是B站今天调整了相关API，不再返回真实有效的注册时间导致的。

**Comment by ALICEOFALICE** [comment]
已经了解，感谢
