### ISSUE TITLE
图形验证码识别开源

### ISSUE THREAD

**Issue by liyongming1982** [Hsury/Bilibili-Toolkit#15]
非常棒的项目
https://bili.dev:2233/captcha , 会考虑开源代码么

**Comment by liyongming1982** [comment]
登录验证码识别结果: NMDNG
 {'ts': 1580735433, 'message': '验证码错误', 'code': -105}

**Comment by Hsury** [comment]
请戳https://github.com/kerlomz/captcha_trainer

**Comment by liyongming1982** [comment]
thank you so much!!!
