### ISSUE TITLE
bilibili修改了网站规则，由AV号改为了BV号

### ISSUE THREAD

**Issue by ALICEOFALICE** [Hsury/Bilibili-Toolkit#16]
bilibili修改了网站规则，由AV号改为了BV号

**Comment by mwx2006** [comment]
api基本上没有变化，只需要把aid换成bvid就行了

**Comment by ALICEOFALICE** [comment]
对，直接替换所有av为bv即可

**Comment by allenfengjr** [comment]
是需要修改全部的文件吗？不只是py中的？

**Comment by mwx2006** [comment]
py中的就行了吧

**Comment by ALICEOFALICE** [comment]
我只改了py中的，跑起来基本没问题

**Comment by allenfengjr** [comment]
> py中的就行了吧

大佬我看你在另一个讨论里的回复那个url，为什么我这里没有那个url？
     是   url = f"{self.protocol}://api.bilibili.com/x/web-interface/view?aid={aid}"这种的？

**Comment by mwx2006** [comment]
这个api是获取视频详细的

**Comment by allenfengjr** [comment]
> 这个api是获取视频详细的

没搜索到...我先试试把av改成bv和aid改bvid试试吧

**Comment by mwx2006** [comment]
https://api.bilibili.com/x/web-interface/view?bvid=BVxxx
新版api类似长这样

**Comment by allenfengjr** [comment]
> https://api.bilibili.com/x/web-interface/view?bvid=BVxxx
> 新版api类似长这样
我修改了URL，其余都未改动，现在config文件无法加载了...

**Comment by ALICEOFALICE** [comment]
是不是config里面的没改啊，默认命名应该是aid，现在你改成bvid了就找不到aid了

**Comment by allenfengjr** [comment]
> 是不是config里面的没改啊，默认命名应该是aid，现在你改成bvid了就找不到aid了
我在py里面只改了url，没改动变量名，是这样的url = f"{self.protocol}://api.bilibili.com/x/web-interface/view?bvid={aid}"。我在config里修改aid时，最初默认的数字aid可以，但现在的是bvid，带有字母的就会出错

**Comment by allenfengjr** [comment]
> 是不是config里面的没改啊，默认命名应该是aid，现在你改成bvid了就找不到aid了

大佬是怎么解决的？

**Comment by allenfengjr** [comment]
刚发现我还修改了一些地方，比如
'Referer': f"https://www.bilibili.com/video/bv{aid}",
但我觉得这应该不是问题所在吧，求指点🙏
