### ISSUE TITLE
请问要如何新添加功能呢？

### ISSUE THREAD

**Issue by Shadyree** [Hsury/Bilibili-Toolkit#24]
我在config.toml中添加了新的方法
[get_image]
enable = true 
user_input = ["6823116"] 

然后在bilibili.py中写了方法，但是不知道是怎么进行调用的
export_process = Process(target=export, args=(queue, config))
export_process.start()
是在这里进行的调用吗？调试没有看到怎么进行的，望大佬解答。

**Comment by Hsury** [comment]
通过[启动新线程](https://github.com/Hsury/Bilibili-Toolkit/blob/ad9ce6f9e53486bea5852cae9f44669700724d1c/bilibili.py#L1439)进行调用~
