### ISSUE TITLE
吐槽下。。。。。感觉好不走心。。。。。

### ISSUE THREAD

**Issue by zuosc** [Hsury/Bilibili-Toolkit#25]
使用Docker版本那块。

1、如果挂载配置文件。在容器启动的时候，会git更新，然后就会代码冲突。。。所以docker镜像可以更新了。。。

2、然后如果配置文件的任意一个配置缺失，就会各种抛弃异常。。。。  读不到配置，默认就不开启，不好么？

感觉好不走心。。。。。

**Comment by Hsury** [comment]
叔叔我啊，真的要不走心了 σ`∀´)
不是，你既不好好提建议，又不自己动手改好来贡献个PR，怎么就搁这嫌弃人呢 (ﾟ∀。)

**Comment by zuosc** [comment]
@Hsury https://github.com/Hsury/Bilibili-Toolkit/pull/27
