### ISSUE TITLE
会员购抢购无法正常使用

### ISSUE THREAD

**Issue by pt4300** [Hsury/Bilibili-Toolkit#26]
行数995的url get request所返回的反应是空的，经过几个测试几个商品之后获取的结果都为相同，不知道是url地址出错了还是其他原因，希望大佬能够修复一下
![image](https://user-images.githubusercontent.com/43430730/89090810-9ee67c00-d3e8-11ea-9827-9abd688ead5b.png)

**Comment by Hsury** [comment]
现在抢购场景相比前两年少了很多，而且基本都有人机验证，没什么改的动力= =
