### ISSUE TITLE
用于定时抢购功能，启动后报错

### ISSUE THREAD

**Issue by WXingSong** [Hsury/Bilibili-Toolkit#40]
![微信图片_20210713114048](https://user-images.githubusercontent.com/37019921/128980452-36522bd4-418a-4452-b47b-354ccf998198.jpg)

**Comment by sheldonl3** [comment]
同样的问题，请问解决了吗？

**Comment by WXingSong** [comment]
> 同样的问题，请问解决了吗？

估计是系统兼容的问题，我用win10直接运行没报错，win7不行
